version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: spring0836
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker0836
      MYSQL_DATABASE: spring0836
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  docker-to-aws-detalhe:
    image: docker-to-aws-detalhe
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo    
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network  
networks:
    udemy-network:
        driver: bridge